export const LOAD_FIELD_SUCCESS = 'LOAD_FIELD_SUCCESS';
export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const DRAW_CARD_SUCCESS = 'DRAW_CARD_SUCCESS';
export const VIEW_CARD = 'VIEW_CARD';
