export const LOAD_FIELD_SUCCESS = 'LOAD_FIELD_SUCCESS';
export const LOAD_HAND_SUCCESS = 'LOAD_HAND_SUCCESS';
export const DRAW_CARD_SUCCESS = 'DRAW_CARD_SUCCESS';
export const REMOVE_CARD_FROM_HAND = 'REMOVE_CARD_FROM_HAND';
export const VIEW_CARD = 'VIEW_CARD';
export const CLOSE_CARD = 'CLOSE_CARD';
export const PLAY_CARD = 'PLAY_CARD';
export const ACTIVATE_CARD = 'ACTIVATE_CARD';
